date.timezone = UTC

memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 32M

log_errors = On
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

max_execution_time = 59
session.gc_maxlifetime = 2400

opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

xdebug.mode = coverage,debug,develop
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
